### ISSUE TITLE
Wrong and missing metrics for Pod

### ISSUE THREAD

**Issue by chrs1885** [CocoaPods/metrics.cocoapods.org#47] opened 2018-10-06 15:57 UTC
It seems like the CocoaPods.org page for my pod does not reflect the correct github metrics.
The page https://cocoapods.org/pods/Capable indicates that there a none GH stars. When visiting the github repo it turns out that there are already 31 of them. Also download statistics do not show up.

**Comment by codeface-io** [comment] 2018-12-28 22:17
Yep, github stats don't update (since at least april) and my pod never had any cocoadocs quality metrics, which seem to be broken for many other repos as well.

Regarding the github stats, i think this issue is a duplicate of https://github.com/CocoaPods/metrics.cocoapods.org/issues/45

**Comment by amorde** [comment] 2019-01-02 19:21
Yup, going to close in favor of #45

**Closed as completed by amorde** 2019-01-02 19:21 UTC
